import { NextRequest, NextResponse } from 'next/server';
import { verifyAuthToken, AUTH_COOKIE_NAME } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { sendEmail } from '@/lib/email';

interface RouteContext {
  params: Promise<{ id: string }>;
}

export async function POST(request: NextRequest, context: RouteContext) {
  try {
    const token =
      request.cookies.get(AUTH_COOKIE_NAME)?.value ||
      request.headers.get('Authorization')?.replace('Bearer ', '') ||
      null;

    if (!token) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const payload = await verifyAuthToken(token);
    if (!payload || payload.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const params = await context.params;
    const applicationId = params.id;

    // Fetch the application
    const application = await prisma.affiliateApplication.findUnique({
      where: { id: applicationId },
    });

    if (!application) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }

    if (application.status !== 'PENDING') {
      return NextResponse.json(
        { error: 'Application has already been processed' },
        { status: 400 }
      );
    }

    // Check if user exists (should exist from application submission)
    const user = await prisma.user.findUnique({
      where: { email: application.email },
      include: {
        influencerProfile: true,
      },
    });

    if (!user || !user.influencerProfile) {
      return NextResponse.json(
        { error: 'Influencer account not found. Please ensure the application was submitted correctly.' },
        { status: 400 }
      );
    }

    // Update application status to approved
    await prisma.affiliateApplication.update({
      where: { id: applicationId },
      data: {
        status: 'APPROVED',
        reviewedBy: payload.userId,
        reviewedAt: new Date(),
      },
    });

    // Send approval confirmation email
    const loginUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #9333ea 0%, #ec4899 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px; }
            .button { display: inline-block; background: linear-gradient(135deg, #9333ea 0%, #ec4899 100%); color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; margin-top: 20px; }
            .footer { text-align: center; margin-top: 30px; color: #6b7280; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>🎉 Application Approved!</h1>
            </div>
            <div class="content">
              <p>Congratulations! Your affiliate application has been approved.</p>
              <p>You can now access your influencer dashboard and start promoting. Your promo code will be sent to you once it's generated by the admin.</p>

              <div style="text-align: center;">
                <a href="${loginUrl}/influencer" class="button">Go to Dashboard</a>
              </div>

              <div class="footer">
                <p>If you have any questions, please contact our affiliate support team.</p>
                <p>Welcome to the Step & Style family! 🚀</p>
              </div>
            </div>
          </div>
        </body>
      </html>
    `;

    try {
      await sendEmail({
        to: application.email,
        subject: 'Step & Style Affiliate Application Approved!',
        html: emailHtml,
      });
    } catch (emailError) {
      console.error('Failed to send approval email:', emailError);
      // Don't fail the request if email fails
    }

    return NextResponse.json({
      success: true,
      message: 'Application approved successfully',
    });
  } catch (error) {
    console.error('Error approving affiliate application:', error);
    return NextResponse.json(
      { error: 'Failed to approve application' },
      { status: 500 }
    );
  }
}

